name: Codacy Analysis & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-and-coverage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Verify Flutter installation
        run: flutter doctor -v

      - name: Run Flutter analyze
        run: flutter analyze --no-fatal-infos

      - name: Run tests with coverage
        run: |
          flutter test --coverage
          
      - name: Upload coverage to Codacy
        if: github.event_name == 'push'
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          if [ -f coverage/lcov.info ]; then
            curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux"))) | .[0].browser_download_url')"
            chmod +x codacy-coverage-reporter
            ./codacy-coverage-reporter report \
              -l Dart \
              -r coverage/lcov.info \
              --project-token "$CODACY_PROJECT_TOKEN"
          else
            echo "No coverage file found at coverage/lcov.info"
          fi